default_platform(:ios)

platform :ios do
  desc "Update Metadata. No Update Build"
  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: false,
      force: true,
      metadata_path: "./fastlane/metadata",
	  screenshots_path: "./fastlane/metadata"
    )
  end
end
