default_platform(:ios)

platform :ios do
  desc "Update Metadata. No Update Build"
  lane :upload_metadata do
  run_precheck_before_submit false
    deliver(
	    app_identifier: "com.Housing-FarmPlanner",
      username: "tasnimruwaida576@gmail.com",
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: false,
      force: true,
      metadata_path: "./fastlane/metadata",
	  screenshots_path: "./fastlane/screenshots"
    )
  end
end
