default_platform(:ios)

platform :ios do
  desc "Update Metadata. No Update Build"
  lane :upload_metadata do
    deliver(
	  app_identifier: "com.Housing-FarmPlanner",
      username: "tasnimruwaida576@gmail.com",
      skip_binary_upload: true,
      skip_metadata: false,
      skip_screenshots: true,
      force: true,
	  edit_live: true,
      metadata_path: "./fastlane/metadata",
    )
  end
end